// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/App.tsx";
import * as $$1 from "./islands/Auth.tsx";
import * as $$2 from "./islands/Avatar.tsx";
import * as $$3 from "./islands/Profile.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/App.tsx": $$0,
    "./islands/Auth.tsx": $$1,
    "./islands/Avatar.tsx": $$2,
    "./islands/Profile.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
